### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by CYBERDEVILZ** [CYBERDEVILZ/YoutubeBot#22]
Add an appropriate LICENSE to this repository. MIT is preferred

**Comment by shadmankhan** [comment]
Hi @CYBERDEVILZ, I would like to take it up

**Comment by askalik** [comment]
@CYBERDEVILZ i believe i have completed this via PR #23

**Comment by CYBERDEVILZ** [comment]
Hi @shadmankhan ,
You can start working on other issue. Sadly this issue has been resolved :(
