### ISSUE TITLE
create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by CYBERDEVILZ** [CYBERDEVILZ/YoutubeBot#35]
If anyone could help me create CONTRIBUTING.md file for this repo, that would be awesome! I literally can't take some time off my coding and focus on the non coding aspect. So the help is much appreciated.

**Comment by satyamgupta1495** [comment]
Hey! How do you like it to be? I mean your CONTRIBUTING.md file. I think I can help you with that

**Comment by arayush841** [comment]
Hey, I've opened a PR regarding this issue. Lmk if it helps!

**Comment by CYBERDEVILZ** [comment]
This issue has been closed. Here is the PR by @arayush841: #36
