### ISSUE TITLE
Windows size to be reduced

### ISSUE THREAD

**Issue by arayush841** [CYBERDEVILZ/YoutubeBot#7]
![image](https://user-images.githubusercontent.com/55954300/134917803-cf5eeb5a-0748-49c9-9eaf-50afc4df2e53.png)

The window size is quite big, couldn't get the field to enter duration and number of loops.

**Comment by CYBERDEVILZ** [comment]
@arayush841 ,
I have made some changes in gui branch. Mind looking into it and inform is something goes wrong.

https://github.com/CYBERDEVILZ/YoutubeBot/tree/gui

**Comment by arayush841** [comment]
@CYBERDEVILZ ,
Hey I checked the YouTubeBotcopy.py file, I guess with 1366x768 the taskbar is blocking the duration and loop field. 

![image](https://user-images.githubusercontent.com/55954300/135026619-8c1e8071-5b0a-47b7-94ab-b20638fb46a2.png)

**Comment by CYBERDEVILZ** [comment]
You know what i think is, the thumbnail is too big for this screen, gotta find a way to dynamically reduce it

**Comment by CYBERDEVILZ** [comment]
I made changes again
fingers crossed

**Comment by arayush841** [comment]
@CYBERDEVILZ ,

Now it works perfectly fine, good job.
![image](https://user-images.githubusercontent.com/55954300/135028497-0ae8d280-d3a7-49d0-8503-d73e9829c945.png)
